# Generated by Django 4.2.2 on 2023-07-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CO', 'Commercial'), ('SU', 'Support'), ('GE', 'Gestion')], max_length=2),
        ),
    ]
